# Generated by Django 3.1.5 on 2021-01-27 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_user', '0002_auto_20210127_1109'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='deathuser',
            table='death_user',
        ),
    ]
