# Generated by Django 3.1.5 on 2021-01-28 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('death_user', '0003_auto_20210127_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deathuser',
            options={'verbose_name': 'death 사용자', 'verbose_name_plural': 'death 사용자'},
        ),
    ]
