# Generated by Django 3.1.5 on 2021-01-28 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('death_user', '0004_auto_20210128_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='deathuser',
            name='useremail',
            field=models.EmailField(default='test@gmail.com', max_length=128, verbose_name='사용자이메일'),
            preserve_default=False,
        ),
    ]
