# Generated by Django 4.0.1 on 2022-01-18 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0002_fcuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('admin', 'admin'), ('user', 'user')], max_length=8, verbose_name='등급'),
        ),
    ]
