# Generated by Django 4.0.1 on 2022-01-18 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcuser', '0003_alter_fcuser_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fcuser',
            name='level',
            field=models.CharField(choices=[('user', 'user'), ('admin', 'admin')], max_length=8, verbose_name='등급'),
        ),
        migrations.AlterField(
            model_name='fcuser',
            name='password',
            field=models.CharField(max_length=100, verbose_name='비밀번호'),
        ),
    ]
