# Generated by Django 3.1.5 on 2021-02-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tag', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'verbose_name': 'death 태그', 'verbose_name_plural': 'death 태그'},
        ),
    ]
